{
  "swagger": "2.0",
  "info": {
    "version": "1.0.0",
    "title": "Reclamask API",
    "description": "API documentation for Reclamask project"
  },
  "host": "localhost:3000",
  "basePath": "",
  "schemes": [
    "http"
  ],
  "consumes": [
    "application/json"
  ],
  "produces": [
    "application/json"
  ],
  "paths": {
    "/user": {
      "post": {
        "tags": [
          "Usuários"
        ],
        "summary": "Cria um novo usuário",
        "description": "Cria um novo usuário com os dados fornecidos.",
        "parameters": [
          {
            "name": "body",
            "in": "body",
            "description": "Dados do novo usuário",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "user_username": {
                  "type": "string",
                  "example": "usuario"
                },
                "user_email": {
                  "type": "string",
                  "example": "usuario@email.com"
                },
                "user_documento": {
                  "type": "string",
                  "example": "12345678900"
                },
                "user_password": {
                  "type": "string",
                  "example": "senha123"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Usuário criado com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Usuário criado"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400": {
            "description": "Dados inválidos",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Erro de validação nos dados fornecidos"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Erro ao criar usuário"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/getUser": {
      "get": {
        "tags": [
          "Usuários"
        ],
        "summary": "Obtém todos os usuários",
        "description": "Retorna uma lista de todos os usuários cadastrados.",
        "responses": {
          "200": {
            "description": "Lista de usuários",
            "schema": {
              "type": "array",
              "items": {
                "type": "object",
                "properties": {
                  "id": {
                    "type": "number",
                    "example": 2
                  },
                  "user_username": {
                    "type": "string",
                    "example": "usuario2"
                  },
                  "user_email": {
                    "type": "string",
                    "example": "usuario2@email.com"
                  },
                  "user_documento": {
                    "type": "string",
                    "example": "98765432100"
                  },
                  "user_tipo": {
                    "type": "number",
                    "example": 1
                  }
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "401": {
            "description": "Não autorizado",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Token inválido ou ausente"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Erro ao buscar usuários"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/getUser/{id}": {
      "get": {
        "tags": [
          "Usuários"
        ],
        "summary": "Obtém um usuário pelo ID",
        "description": "Retorna os dados de um usuário específico com base no ID fornecido.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "ID do usuário a ser buscado",
            "example": 1
          }
        ],
        "responses": {
          "200": {
            "description": "Dados do usuário",
            "schema": {
              "type": "object",
              "properties": {
                "id": {
                  "type": "number",
                  "example": 1
                },
                "user_username": {
                  "type": "string",
                  "example": "usuario1"
                },
                "user_email": {
                  "type": "string",
                  "example": "usuario1@email.com"
                },
                "user_documento": {
                  "type": "string",
                  "example": "12345678900"
                },
                "user_tipo": {
                  "type": "number",
                  "example": 1
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "403": {
            "description": "Acesso negado",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Permissão insuficiente"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Usuário não encontrado"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Erro ao buscar usuário"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/user/{id}": {
      "put": {
        "tags": [
          "Usuários"
        ],
        "summary": "Atualiza os dados de um usuário",
        "description": "Atualiza um usuário existente com base no ID fornecido.",
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "type": "integer",
            "description": "ID do usuário a ser atualizado",
            "example": 1
          },
          {
            "name": "body",
            "in": "body",
            "description": "Dados do usuário a serem atualizados",
            "required": true,
            "schema": {
              "type": "object",
              "properties": {
                "user_username": {
                  "type": "string",
                  "example": "novousuario"
                },
                "user_email": {
                  "type": "string",
                  "example": "usuario@email.com"
                },
                "user_documento": {
                  "type": "string",
                  "example": "12345678900"
                },
                "user_tipo": {
                  "type": "number",
                  "example": 1
                },
                "user_password": {
                  "type": "string",
                  "example": "senha123"
                }
              }
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Usuário atualizado com sucesso",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Usuário atualizado"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "400": {
            "description": "Dados inválidos",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Erro de validação nos dados fornecidos"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "404": {
            "description": "Usuário não encontrado",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "ID não localizado"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          },
          "500": {
            "description": "Erro interno do servidor",
            "schema": {
              "type": "object",
              "properties": {
                "mensagem": {
                  "type": "string",
                  "example": "Erro ao atualizar usuário"
                }
              },
              "xml": {
                "name": "main"
              }
            }
          }
        }
      }
    },
    "/login": {
      "post": {
        "tags": [
          "Login"
        ],
        "summary": "Realiza o login do usuário",
        "description": "Realiza o login do usuário com as credenciais fornecidas.",
        "parameters": [
          {
            "name": "authorization",
            "in": "header",
            "type": "string"
          },
          {
            "name": "body",
            "in": "body",
            "schema": {
              "type": "object",
              "properties": {
                "user_doc": {
                  "example": "any"
                },
                "user_password": {
                  "example": "any"
                }
              }
            }
          }
        ],
        "responses": {
          "201": {
            "description": "Criado"
          },
          "400": {
            "description": "Solicitação Inválida"
          },
          "500": {
            "description": "Erro Interno do Servidor"
          }
        }
      }
    }
  }
}